YOLOV3:
  CFG: "./alg/excavator/detector/YOLOv3/cfg/yolo_v3.cfg"
  WEIGHT: "./alg/excavator/detector/YOLOv3/weight/yolov3.weights"
  CLASS_NAMES: "./alg/excavator/detector/YOLOv3/cfg/coco.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4
