YOLOV3:
  CFG: "./alg/excavator/detector/YOLOv3/cfg/yolov3-tiny.cfg"
  WEIGHT: "./alg/excavator/detector/YOLOv3/weight/yolov3-tiny.weights"
  CLASS_NAMES: "./alg/excavator/detector/YOLOv3/cfg/coco.names"

  SCORE_THRESH: 0.5
  NMS_THRESH: 0.4